# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('age', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type_animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type_cage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo.Cage'),
        ),
        migrations.AddField(
            model_name='animal',
            name='type_animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo.Type_animal'),
        ),
        migrations.AddField(
            model_name='animal',
            name='type_cage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo.Type_cage'),
        ),
    ]
