# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0002_cage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(choices=[('Dog', 'dog'), ('Cat', 'cat')], max_length=30, null=True),
        ),
    ]
