# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0003_auto_20180212_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='type_animal',
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(choices=[('Lion', 'lion'), ('Elephant', 'elephant'), ('Monkey', 'monkey'), ('Flamingo', 'flamingo'), ('Giraffe', 'giraffe')], max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Type_animal',
        ),
    ]
