# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0005_auto_20180212_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='type_cage',
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Type_cage',
        ),
    ]
