# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 13:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zoo', '0006_auto_20180213_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='highlighted',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Animal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cage',
            name='highlighted',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cage',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cage',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
