# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0007_auto_20180213_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='zoo.Cage'),
        ),
    ]
